export const listChats = [
  {
    id: "1",
    imageUrl: require("./images/avatars/alice-freeman.jpg"),
    title: "Alice Freeman",
    createdAt: "Apr 16",
    latestMessageText: "Sorry to hear that.",
    messages: [
      {
        id: "111",
        imageUrl: null,
        name: null,
        messageText: "Hi, Alice!",
        createdAt: "Apr 16",
        isMyMessage: true,
      },
      {
        id: "112",
        imageUrl: require("./images/avatars/alice-freeman.jpg"),
        name: "Alice Freeman",
        messageText: "Hi, Iryna!",
        createdAt: "Apr 16",
        isMyMessage: false,
      },
      {
        id: "113",
        imageUrl: null,
        name: null,
        messageText:
          "It’s a long time since I saw you last. Where have you been all this time?",
        createdAt: "Apr 15",
        isMyMessage: true,
      },
      {
        id: "114",
        imageUrl: require("./images/avatars/alice-freeman.jpg"),
        name: "Alice Freeman",
        messageText: "I have just returned from Canada.",
        createdAt: "Apr 15",
        isMyMessage: false,
      },
      {
        id: "115",
        imageUrl: null,
        name: null,
        messageText: "Was it a business trip?",
        createdAt: "Apr 15",
        isMyMessage: true,
      },
      {
        id: "116",
        imageUrl: require("./images/avatars/alice-freeman.jpg"),
        name: "Alice Freeman",
        messageText: "Exactly.",
        createdAt: "Apr 15",
        isMyMessage: false,
      },
      {
        id: "117",
        imageUrl: null,
        name: null,
        messageText: "I hope it was successful.",
        createdAt: "Apr 13",
        isMyMessage: true,
      },
      {
        id: "118",
        imageUrl: require("./images/avatars/alice-freeman.jpg"),
        name: "Alice Freeman",
        messageText: "I am afraid not.",
        createdAt: "Apr 13",
        isMyMessage: false,
      },
      {
        id: "119",
        imageUrl: null,
        name: null,
        messageText: "Sorry to hear that.",
        createdAt: "Apr 13",
        isMyMessage: true,
      },
    ],
  },
  {
    id: "2",
    imageUrl: require("./images/avatars/josefina.jpg"),
    title: "Josefina",
    createdAt: "Oct 20",
    latestMessageText: "Thank you. Take care!.",
    messages: [
      {
        id: "211",
        imageUrl: null,
        name: null,
        messageText: "Are you flying to Baltimore?",
        createdAt: "Apr 16",
        isMyMessage: true,
      },
      {
        id: "212",
        imageUrl: require("./images/avatars/josefina.jpg"),
        name: "Josefina",
        messageText: "Yes, the plane takes off in an hour.",
        createdAt: "Apr 16",
        isMyMessage: false,
      },
      {
        id: "213",
        imageUrl: null,
        name: null,
        messageText: "Have a happy landing.",
        createdAt: "Apr 15",
        isMyMessage: true,
      },
      {
        id: "214",
        imageUrl: require("./images/avatars/josefina.jpg"),
        name: "Josefina",
        messageText: "Thank you. Take care!",
        createdAt: "Apr 15",
        isMyMessage: false,
      },
    ],
  },
  {
    id: "3",
    imageUrl: require("./images/avatars/velazquez.jpg"),
    title: "Velazquez",
    createdAt: "1 week ago",
    latestMessageText: "All right. Till Saturday. Good-bye.",
    messages: [
      {
        id: "311",
        imageUrl: null,
        name: null,
        messageText: "Hello, Velazquez. How are you?",
        createdAt: "Apr 16",
        isMyMessage: true,
      },
      {
        id: "312",
        imageUrl: require("./images/avatars/velazquez.jpg"),
        name: "Velazquez",
        messageText: "No complaints. Thanks. How is life treating you?",
        createdAt: "Apr 16",
        isMyMessage: false,
      },
      {
        id: "313",
        imageUrl: null,
        name: null,
        messageText: "I am doing fine. Thank you. Are you engaged on Saturday?",
        createdAt: "Apr 15",
        isMyMessage: true,
      },
      {
        id: "314",
        imageUrl: require("./images/avatars/velazquez.jpg"),
        name: "Velazquez",
        messageText: "No, I am not. Why?",
        createdAt: "Apr 15",
        isMyMessage: false,
      },
      {
        id: "315",
        imageUrl: null,
        name: null,
        messageText:
          "I want to invite you and your wife Helen to come and dine with us. We shall be delighted.",
        createdAt: "Apr 15",
        isMyMessage: true,
      },
      {
        id: "316",
        imageUrl: require("./images/avatars/velazquez.jpg"),
        name: "Velazquez",
        messageText: "Thank you for the invitation. What’s the occasion?",
        createdAt: "Apr 15",
        isMyMessage: false,
      },
      {
        id: "317",
        imageUrl: null,
        name: null,
        messageText: "It will be my wife’s birthday.",
        createdAt: "Apr 13",
        isMyMessage: true,
      },
      {
        id: "318",
        imageUrl: require("./images/avatars/velazquez.jpg"),
        name: "Velazquez",
        messageText: "We will be pleased to come.",
        createdAt: "Apr 13",
        isMyMessage: true,
      },
      {
        id: "319",
        imageUrl: null,
        name: null,
        messageText: "Do you know my address?",
        createdAt: "Apr 13",
        isMyMessage: true,
      },
      {
        id: "320",
        imageUrl: require("./images/avatars/velazquez.jpg"),
        name: "Velazquez",
        messageText: "Sure. What time do you want us to come?",
        createdAt: "Apr 13",
        isMyMessage: true,
      },
      {
        id: "321",
        imageUrl: null,
        name: null,
        messageText: "We expect you at 7 p.m.",
        createdAt: "Apr 13",
        isMyMessage: true,
      },
      {
        id: "322",
        imageUrl: require("./images/avatars/velazquez.jpg"),
        name: "Velazquez",
        messageText: "All right. Till Saturday. Good-bye.",
        createdAt: "Apr 13",
        isMyMessage: true,
      },
    ],
  },
  {
    id: "4",
    imageUrl: require("./images/avatars/barrera.png"),
    title: "Barrera",
    createdAt: "2:49 PM",
    latestMessageText: "Thanks.",
    messages: [
      {
        id: "411",
        imageUrl: require("./images/avatars/barrera.png"),
        name: "Barrera",
        messageText: "Hello, are you home yet?",
        createdAt: "Apr 16",
        isMyMessage: false,
      },
      {
        id: "412",
        imageUrl: null,
        name: null,
        messageText: "Hello. No, I'm still at work.",
        createdAt: "Apr 15",
        isMyMessage: true,
      },
      {
        id: "413",
        imageUrl: require("./images/avatars/barrera.png"),
        name: "Barrera",
        messageText: "Call me when you get home.",
        createdAt: "Apr 15",
        isMyMessage: false,
      },
      {
        id: "414",
        imageUrl: null,
        name: null,
        messageText: "Ok.",
        createdAt: "Apr 15",
        isMyMessage: true,
      },
      {
        id: "415",
        imageUrl: require("./images/avatars/barrera.png"),
        name: "Barrera",
        messageText: "Thanks.",
        createdAt: "Apr 15",
        isMyMessage: false,
      },
    ],
  },
  {
    id: "5",
    imageUrl: require("./images/avatars/mark.jpg"),
    title: "Mark",
    createdAt: "6:14 PM",
    latestMessageText: "Yes, but I like to watch basketball.",
    messages: [
      {
        id: "511",
        imageUrl: null,
        name: null,
        messageText: "Hello, Mark! What are you doing?",
        createdAt: "Apr 16",
        isMyMessage: true,
      },
      {
        id: "512",
        imageUrl: require("./images/avatars/mark.jpg"),
        name: "Mark",
        messageText: "Hello, Iryna. I'm going to the gym right now.",
        createdAt: "Apr 16",
        isMyMessage: false,
      },
      {
        id: "513",
        imageUrl: null,
        name: null,
        messageText: "Really? Which?",
        createdAt: "Apr 15",
        isMyMessage: true,
      },
      {
        id: "514",
        imageUrl: require("./images/avatars/mark.jpg"),
        name: "Mark",
        messageText:
          "New. It was opened last week next to the Jasmin's hair salon.",
        createdAt: "Apr 15",
        isMyMessage: false,
      },
      {
        id: "515",
        imageUrl: null,
        name: null,
        messageText:
          "Ok, will you call me back when you get home? If you like this gym, I will join you tomorrow.",
        createdAt: "Apr 15",
        isMyMessage: true,
      },
      {
        id: "516",
        imageUrl: require("./images/avatars/mark.jpg"),
        name: "Mark",
        messageText:
          "I'm going to the basketball game tomorrow. My team is poorly prepared and I need to support them.",
        createdAt: "Apr 15",
        isMyMessage: false,
      },
      {
        id: "517",
        imageUrl: null,
        name: null,
        messageText: "Oh, I'll definitely join you on that one. Do you mind?",
        createdAt: "Apr 13",
        isMyMessage: true,
      },
      {
        id: "518",
        imageUrl: require("./images/avatars/mark.jpg"),
        name: "Mark",
        messageText:
          "No, of course not. But I thought you were on the football team.",
        createdAt: "Apr 13",
        isMyMessage: false,
      },
      {
        id: "519",
        imageUrl: null,
        name: null,
        messageText: "Yes, but I like to watch basketball.",
        createdAt: "Apr 13",
        isMyMessage: true,
      },
    ],
  },
  {
    id: "6",
    imageUrl: require("./images/avatars/fil-potter.jpg"),
    title: "Fil Potter",
    createdAt: "3 secs ago",
    latestMessageText: "Sure, i’ll you wait in the canteen.",
    messages: [
      {
        id: "611",
        imageUrl: null,
        name: null,
        messageText: "Good afternoon, Fil, how is your day going?",
        createdAt: "Apr 16",
        isMyMessage: true,
      },
      {
        id: "612",
        imageUrl: require("./images/avatars/fil-potter.jpg"),
        name: "Fil Potter",
        messageText: "I’m finishing the report. And what about you?",
        createdAt: "Apr 16",
        isMyMessage: false,
      },
      {
        id: "613",
        imageUrl: null,
        name: null,
        messageText:
          "And I have to finish the project, today is the deadline. But i’m going to take a short break soon and drop in the canteen.",
        createdAt: "Apr 15",
        isMyMessage: true,
      },
      {
        id: "614",
        imageUrl: require("./images/avatars/fil-potter.jpg"),
        name: "Fil Potter",
        messageText: "Great, I didn’t have a lunch today. Can I join you?",
        createdAt: "Apr 15",
        isMyMessage: false,
      },
      {
        id: "615",
        imageUrl: null,
        name: null,
        messageText: "Sure.",
        createdAt: "Apr 15",
        isMyMessage: true,
      },
      {
        id: "616",
        imageUrl: require("./images/avatars/fil-potter.jpg"),
        name: "Fil Potter",
        messageText:
          "Listen, are you working with Ellen on this project of yours?",
        createdAt: "Apr 15",
        isMyMessage: false,
      },
      {
        id: "617",
        imageUrl: null,
        name: null,
        messageText: "Aha, how do you know?",
        createdAt: "Apr 13",
        isMyMessage: true,
      },
      {
        id: "618",
        imageUrl: require("./images/avatars/fil-potter.jpg"),
        name: "Fil Potter",
        messageText:
          "Well, I saw her today doing nothing and thought that she is with someone responsible in the team. Why don’t you give her any tasks?",
        createdAt: "Apr 13",
        isMyMessage: false,
      },
      {
        id: "619",
        imageUrl: null,
        name: null,
        messageText:
          "Don’t ask. Believe me, it is the last time i’m doing the project with her. I work twice faster when she is no around.",
        createdAt: "Apr 13",
        isMyMessage: true,
      },
      {
        id: "620",
        imageUrl: require("./images/avatars/fil-potter.jpg"),
        name: "Fil Potter",
        messageText:
          "I understand you, she is something! I think she will be transferred to another department soon. The manager knows everything.",
        createdAt: "Apr 13",
        isMyMessage: false,
      },
      {
        id: "621",
        imageUrl: null,
        name: null,
        messageText: "Good for her, the job here is too difficult for Ellen.",
        createdAt: "Apr 13",
        isMyMessage: true,
      },
      {
        id: "622",
        imageUrl: require("./images/avatars/fil-potter.jpg"),
        name: "Fil Potter",
        messageText: "Ok, then i’ll see you in 10 minutes?",
        createdAt: "Apr 13",
        isMyMessage: false,
      },
      {
        id: "623",
        imageUrl: null,
        name: null,
        messageText: "Sure, i’ll you wait in the canteen.",
        createdAt: "Apr 13",
        isMyMessage: true,
      },
    ],
  },
  {
    id: "7",
    imageUrl: require("./images/avatars/helen.jpg"),
    title: "Helen",
    createdAt: "30 mins ago",
    latestMessageText: "I am from France.",
    messages: [
      {
        id: "711",
        imageUrl: require("./images/avatars/helen.jpg"),
        name: "Helen",
        messageText: "Hi! How are you?",
        createdAt: "Apr 16",
        isMyMessage: false,
      },
      {
        id: "712",
        imageUrl: null,
        name: null,
        messageText: "Fine, thanks. And you?",
        createdAt: "Apr 15",
        isMyMessage: true,
      },
      {
        id: "713",
        imageUrl: require("./images/avatars/helen.jpg"),
        name: "Helen",
        messageText: "So so. Where are you from?",
        createdAt: "Apr 15",
        isMyMessage: false,
      },
      {
        id: "714",
        imageUrl: null,
        name: null,
        messageText: "I am from Ukraine. Where are you from?",
        createdAt: "Apr 15",
        isMyMessage: true,
      },
      {
        id: "715",
        imageUrl: require("./images/avatars/helen.jpg"),
        name: "Helen",
        messageText: "I am from France.",
        createdAt: "Apr 15",
        isMyMessage: false,
      },
    ],
  },
];
